### ISSUE TITLE
ACW: delete bulk import doesn’t delete all encounters

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#303] opened 2023-07-24 21:21 UTC
**Expected Behavior**
Deleting a bulk import also deletes the encounters within it.

**Current Behavior**
Deleting a bulk import removes the bulk import from the user's bulk import list, but the encounters remain in ACW. Maureen is unsure if the animals being matched before the import was deleted is a factor. Here's a link to one of the Marked Individuals whose 11 encounters were all in that deleted bulk import and so each should have been deleted: https://africancarnivore.wildbook.org/individuals.jsp?id=eb9bce50-5e6e-4653-a525-abe0eedf744b

**Investigation Notes**
JH and Anastasia tried to replicate this in testing, but our ID’d encounters were still deleted when we deleted the bulk import they came from. 

**Community Link**
https://community.wildme.org/t/acw-delete-bulk-import-doesnt-delete-all-encounters/2082

**Comment by TanyaStere42** [comment] 2024-03-26 18:15
Through initial testing and new testing, unable to reproduce the issue. Closing.

**Closed by TanyaStere42** 2024-03-26 18:15 UTC
Labels: bug
