### ISSUE TITLE
Bulk import should validate that location ID field can match "name" or "id"

### ISSUE THREAD

**Issue by goddesswarship** [WildMeOrg/Wildbook#707] opened 2024-08-27 22:15 UTC
Data in the`Encounter.locationID` field of a bulk import spreadsheet is currently checked against the `name` entry in `locationID.json`. However, when the location names differ between `name` and `id` fields (such as `Rapid River, ME` vs `Rapid River ME`), potential matches are missed. If we update it so that both `name` and `id` are checked, users will see fewer discrepancies with their match candidates.

Related to #711

**Comment by TanyaStere42** [comment] 2024-09-23 19:43
@goddesswarship Is this a duplicate of #709 ?

**Comment by goddesswarship** [comment] 2024-09-30 17:24
@TanyaStere42 Looks like it!

**Comment by TanyaStere42** [comment] 2024-09-30 19:00
closing issue as a duplicate of #709

**Closed by TanyaStere42** 2024-09-30 19:00 UTC
Labels: duplicate
