### ISSUE TITLE
Individual pages open links inconsistently

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/Wildbook#365] opened 2024-02-07 02:42 UTC
**Expected Behavior**
Links from all `individuals.jsp?id=[guid]` open new tabs to `target=_self`, middle click to `target=_blank`, and right click opens the standard menu

**Current Behavior**
- From a marked individual page, you can't right-click or scroll wheel click to open encounter links in a new tab, but you can ctrl+click or cmd+click.

**Comment by NNattoji** [comment] 2024-03-15 01:08
This has been fixed and tested locally on Safari, Chrome and Firefox. The links show expected behaviour now. The issue was also seen on the Individual Search Results page while fixing the issue on Individuals page. The issue has also been fixed for the Individual Search Results page as part of this ticket since users navigate to Individuals page through this page.

**Comment by NNattoji** [comment] 2024-03-15 01:13
Another existing issue was seen, in the Co-occurrences table on Individuals page, while applying fix for this issue. Individual id is not getting appended properly to the Co-occurrences table links, hence clicking on the table rows does not navigate to proper URLs. 

![Screen Shot 2024-03-14 at 6 09 54 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/8309d3c7-29c1-4888-bf80-a18b47fdcc4e)
![Screen Shot 2024-03-14 at 6 10 15 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/79508d97-6b48-49a9-90a4-2d4bfa67fd15)

This is happening because the individual display name is being used while forming the URL, the id (UUID) is to be used instead. If there is a ticket for this or if a ticket is created, I can create a PR with the fix.

**Comment by NNattoji** [comment] 2024-03-15 01:15
Another existing issue was seen, in the Co-occurrences table on Individuals page, while applying fix for this issue. Individual id is not getting appended properly to the Co-occurrences table links, hence clicking on the table rows does not navigate to proper URLs.
![Screen Shot 2024-03-14 at 6 14 48 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/378a6984-6523-4d18-bea4-1aef44a30f9e)
![Screen Shot 2024-03-14 at 6 14 55 PM](https://github.com/WildMeOrg/Wildbook/assets/20950872/0d4ac9b3-d615-4c21-9ab0-ea96d1ac0aa3)
This is happening because the individual display name is being used while forming the URL, the id (UUID) is to be used instead. If there is a ticket for this or if a ticket is created, I can create a PR with the fix.

**Comment by TanyaStere42** [comment] 2024-03-15 04:39
I believe that problem is https://github.com/WildMeOrg/Wildbook/issues/271

**Closed** 2024-03-18 16:51 UTC
Labels: bug, good first issue

**Comment by NNattoji** [comment] 2024-03-18 17:23
I took a look at #271 today, looks like a different issue.

**Comment by TanyaStere42** [comment] 2024-03-18 17:26
okay, no worries, I'll make a new ticket for what you've reported here in a minute
